---
  - name: Install python if neccessary
    hosts: all
    become: true
    gather_facts: false

    tasks:
      - name: Install python for ansible
        raw: which python || (apt-get update -y apt-get install -y python-minimal)
