---
  - name: Show debug info about variables
    debug:
      msg: "This host belongs to {{ env }} environment and db_host is {{ db_host }}"

  - include: ruby.yml
  - include: config_create.yml
  - include: systemd_unit_create.yml
