---
  - name: Show debug info about variables
    debug:
      msg: "This host belongs to {{ env|default('***env_not_set***') }} environment"
  - include: ruby.yml
  - include: config_create.yml
  - include: systemd_unit_create.yml
