---
- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    mongo_port: 27017
    db_host: 10.166.0.3

  tasks:
    - name: Change mongoDB config file
      become: true
      vars:
        mongo_bind_ip: 0.0.0.0
        mongo_port: 27017
        db_host: 10.166.0.3
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongod

    - name: Create systemd unit file for puma server
      become: true
      copy:
        src: files/puma.service
        dest: /lib/systemd/system/puma.service
      tags: app-tag
      notify: restart puma

    - name: Enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag

    - name: Add config for DB connection
      become: true
      template:
        src: templates/db_config.j2
        dest: /etc/default/puma_db_config
      tags: app-tag

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /usr/local/share/reddit
        version: monolith
      tags: deploy-tag
      notify: restart puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /usr/local/share/reddit
      tags: deploy-tag

  handlers:
    - name: restart mongod
      become: true
      service: name=mongod state=restarted
    - name: restart puma
      become: true
      systemd: name=puma state=restarted
