---
- name: Configure MongoDB
  hosts: db
  vars:
    mongo_bind_ip: 0.0.0.0
    mongo_port: 27017
  become: true

  tasks:
    - name: Change mongoDB config file
      vars:
        mongo_bind_ip: 0.0.0.0
        mongo_port: 27017
        db_host: 10.166.0.3
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
    - name: restart mongod
      become: true
      service: name=mongod state=restarted
