all:
    children:
        app:
            hosts:
                appserver: 
                    ansible_host: 35.228.151.19
        db:
            hosts:
                dbserver:
                     ansible_host: 35.228.67.148
