---
- name: Configure MongoDB
  hosts: db
  vars:
    mongo_bind_ip: 0.0.0.0
    mongo_port: 27017
  become: true
  tags: db-tag

  tasks:
    - name: Change mongoDB config file
      vars:
        mongo_bind_ip: 0.0.0.0
        mongo_port: 27017
        db_host: 10.166.0.3
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
    - name: restart mongod
      become: true
      service: name=mongod state=restarted

- name: Configure Reddit app
  hosts: app
  vars:
    mongo_port: 27017
  tags: app-tag
  become: true
  tasks:
    - name: Create systemd unit file for puma server
      copy:
        src: files/puma.service
        dest: /lib/systemd/system/puma.service
      notify: restart puma

    - name: Enable puma
      systemd: name=puma enabled=yes

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /etc/default/puma_db_config
  handlers:
    - name: restart puma
      systemd: name=puma state=restarted

- name: Deploy Reddit app
  hosts: app
  tags: deploy-tag
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      notify: restart puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit

  handlers:
    - name: restart puma
      become: true
      systemd: name=puma state=restarted
